
name: Run notebooks

on: [pull_request]

jobs:
  alpha1:
    name: Alpha 1
    runs-on: ubuntu-latest
  steps:
    - uses: 'google-github-actions/auth@v2'
      with:
      credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info' 