"""update essay model

Revision ID: 15bb95ed8f00
Revises: a032bd8b0c2e
Create Date: 2024-11-04 20:05:28.846217

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '15bb95ed8f00'
down_revision = 'a032bd8b0c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candiate_exam_essay', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candiate_exam_essay', sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candiate_exam_essay', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candiate_exam_essay', 'score')
    op.drop_column('candiate_exam_essay', 'resource')
    op.drop_column('candiate_exam_essay', 'content')
    # ### end Alembic commands ###
