on: [pull_request]

jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        with:
        access_token_lifetime: 900s
        workload_identity_provider: projects/393517768996/locations/global/workloadIdentityPools/main-pool/providers/github
        service_account: 'sa-xtrading-strategy-service@xtrading-engine-beta.iam.gserviceaccount.com'
        create_credentials_file: true
        activate_credentials_file: true

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
